'use client';
import {useEffect,useRef,useState} from 'react';
import {MapPinned,Plus,MapPin,ClipboardList,ShieldCheck,Wallet,Route,Camera,X,LocateFixed,Check,Layers,Search,RefreshCw,Clock,ChevronRight,TriangleAlert,ArrowUpRight} from 'lucide-react';
import MapView,{Report} from './map-view';
import {listReports,addExamples,createReport,reviseReport} from './storage';
const statuses=['Recibido','En revisión','Validado','Atendido/Cerrado','Descartado'];
const kinds=['Andén bloqueado','Doble fila','Paso peatonal bloqueado','Ciclovía bloqueada','Otro obstáculo'];
const next:Record<string,string[]>={'Recibido':['En revisión','Validado','Descartado'],'En revisión':['Validado','Descartado'],'Validado':['Atendido/Cerrado'],'Atendido/Cerrado':[],'Descartado':[]};
const statusLabel=(s:string)=>({'En revisión':'Por revisar','Validado':'Confirmado','Descartado':'Denegado'} as Record<string,string>)[s]||s;
const klass=(s:string)=>'status s'+statuses.indexOf(s);
const cash=(n:number)=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n);
const date=(d:string)=>new Date(d).toLocaleString('es-CO',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Bogota'});
const earned=(r:Report)=>['Validado','Atendido/Cerrado'].includes(r.status);
function Modal({children,title,onClose,wide=false}:{children:React.ReactNode;title:string;onClose:()=>void;wide?:boolean}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);
 return <dialog ref={ref} className={wide?'modal wide':'modal'} aria-label={title} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-head"><h2>{title}</h2><button className="icon-button" aria-label="Cerrar ventana" onClick={onClose}><X size={22}/></button></div>{children}</dialog>;
}
export default function Workspace(){
 const [reports,setReports]=useState<Report[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState('Mapa de reportes'),[reviewer,setReviewer]=useState(false),[create,setCreate]=useState(false),[selected,setSelected]=useState<Report|null>(null),[status,setStatus]=useState('Todos'),[kind,setKind]=useState('Todas'),[query,setQuery]=useState(''),[heat,setHeat]=useState(false),[busy,setBusy]=useState(false);
 async function refresh(){setError('');setLoading(true);try{const data=await listReports();setReports(data);return data;}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{refresh();},[]);
 async function examples(){setBusy(true);setError('');try{await addExamples();await refresh();setNotice('Cinco reportes ficticios listos para explorar.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const visible=reports.filter(r=>(tab!=='Mis reportes'||!r.example)&&(status==='Todos'||r.status===status)&&(kind==='Todas'||r.kind===kind)&&[r.kind,r.address,r.id].some(v=>v.toLowerCase().includes(query.toLowerCase())));
 const validated=reports.filter(earned),open=reports.filter(r=>!['Atendido/Cerrado','Descartado'].includes(r.status)),pending=reports.filter(r=>['Recibido','En revisión','Validado'].includes(r.status));
 function navigation(name:string){setTab(name);setStatus('Todos');setKind('Todas');setQuery('');}
 return <div className="shell">
 <header className="header"><a className="brand" href="./index.html" aria-label="Vía Libre, inicio"><span className="brand-icon"><Route size={25}/></span><span>Vía Libre<small>Valledupar</small></span></a><nav aria-label="Navegación principal">{[['Mapa de reportes',MapPinned],['Mis reportes',ClipboardList],['Recompensas',Wallet]].map(([name,Icon])=>{const C=Icon as typeof MapPinned;return <button key={String(name)} className={tab===name?'nav active':'nav'} onClick={()=>navigation(String(name))}><C size={18}/>{String(name)}</button>;})}</nav><button className={reviewer?'mode reviewer':'mode'} onClick={()=>{const value=!reviewer;setReviewer(value);navigation(value?'Revisión':'Mapa de reportes');}}><ShieldCheck size={18}/>{reviewer?'Modo revisor':'Probar como revisor'}</button></header>
 <div className="demo-bar"><span className="demo-label">Prueba de concepto</span><span>Datos guardados en este navegador · Revisión y recompensas simuladas.</span><span className="demo-tail">Sin envío a autoridades ni pagos reales</span></div>
 <main>
 <div className="page-heading"><div><p className="place"><MapPin size={15}/> Valledupar, Colombia</p><h1>{tab}</h1><p className="subtitle">{tab==='Revisión'?'Revisa la evidencia y simula una decisión sobre cada reporte.':tab==='Mis reportes'?'Consulta lo que has reportado y sigue cada avance.':tab==='Recompensas'?'Explora cómo funcionaría el reconocimiento por reportes confirmados.':'Ubica los obstáculos y sigue lo que ocurre en la ciudad.'}</p></div><button className="primary" onClick={()=>setCreate(true)}><Plus size={19}/>Nuevo reporte</button></div>
 <div className="metrics"><div><span className="metric-icon"><ClipboardList size={21}/></span><span><strong>{reports.length}</strong><small>Reportes registrados</small></span></div><div><span className="metric-icon amber"><Clock size={21}/></span><span><strong>{open.length}</strong><small>Reportes abiertos</small></span></div><div><span className="metric-icon green"><Check size={22}/></span><span><strong>{reports.filter(r=>r.status==='Atendido/Cerrado').length}</strong><small>Casos cerrados</small></span></div><div><span className="metric-icon green"><Wallet size={21}/></span><span><strong>{cash(validated.length*10000)}<em> ficticios</em></strong><small>Recompensas simuladas</small></span></div></div>
 {error&&<div className="alert" role="alert"><TriangleAlert size={18}/>{error}<button onClick={refresh}>Reintentar</button></div>}{notice&&<div className="notice" role="status">{notice}<button className="icon-button" onClick={()=>setNotice('')} aria-label="Cerrar aviso"><X size={16}/></button></div>}
 {tab==='Recompensas'?<section className="reward-layout"><div className="reward-summary"><Wallet size={34}/><h2>Tu saldo de demostración</h2><strong>{cash(validated.length*10000)}</strong><p>Pesos colombianos ficticios</p><div className="reward-rule">Cada reporte confirmado suma {cash(10000)} de prueba. Cerrar el caso conserva esa recompensa.</div><p className="small">El envío a Nequi se representa únicamente como un abono ficticio. No se solicitan cuentas ni se mueve dinero.</p></div><div className="panel"><div className="panel-title"><h2>Abonos simulados</h2><span>{validated.length} reportes</span></div>{validated.length?validated.map(r=><button className="reward-row" key={r.id} onClick={()=>setSelected(r)}><div><strong>{r.kind}</strong><small>{r.address}{r.example?' · Ejemplo':''}</small></div><div><strong className="money">+ {cash(10000)}</strong><small>Nequi · Simulado</small></div></button>):<div className="empty"><Wallet/><h3>Aún no hay recompensas</h3><p>Confirma un reporte en modo revisor para ver un abono ficticio.</p></div>}</div></section>:<>
 <div className="toolbar"><div className="search"><Search size={18}/><input aria-label="Buscar reportes" placeholder="Buscar por dirección, situación o código" value={query} onChange={e=>setQuery(e.target.value)}/></div><label className="filter"><span>Estado</span><select value={status} onChange={e=>setStatus(e.target.value)}><option>Todos</option>{statuses.map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select></label><label className="filter"><span>Situación</span><select value={kind} onChange={e=>setKind(e.target.value)}><option>Todas</option>{kinds.map(k=><option key={k}>{k}</option>)}</select></label><button className="icon-button refresh" aria-label="Actualizar reportes" onClick={refresh} disabled={loading}><RefreshCw size={18} className={loading?'spin':''}/></button></div>
 <div className={tab==='Mapa de reportes'?'explorer':'list-view'}><section className="report-panel"><div className="panel-title"><h2>{tab==='Revisión'?'Bandeja de revisión':tab==='Mis reportes'?'Tus reportes':'En la ciudad'}</h2><span>{visible.length} {visible.length===1?'reporte':'reportes'}</span></div><div className="report-scroll">
 {loading&&!reports.length?<div className="empty">Cargando reportes…</div>:visible.length?visible.map(r=><button key={r.id} className="report-card" onClick={()=>setSelected(r)}><div className="report-top"><span className={klass(r.status)}>{statusLabel(r.status)}</span><small>{r.example?'Ejemplo':'#'+r.id.slice(0,6).toUpperCase()}</small></div><h3>{r.kind}</h3><p><MapPin size={15}/>{r.address}</p><div className="report-bottom"><span>{date(r.created)}</span><ChevronRight size={17}/></div></button>):<div className="empty"><MapPinned size={30}/><h3>{reports.length?'No hay coincidencias':tab==='Mis reportes'?'Tu primer reporte empieza aquí':'El mapa está listo'}</h3><p>{reports.length?'Prueba con otros filtros.':'Crea un reporte con una foto y ubicación, o explora los ejemplos.'}</p><button className="secondary" onClick={()=>setCreate(true)}>Crear reporte</button></div>}
 </div><div className="sample-footer"><span>Explora el recorrido con datos ficticios.</span><button onClick={examples} disabled={busy}>{busy?'Cargando…':'Cargar ejemplos'}</button></div></section>
 {tab==='Mapa de reportes'&&<section className="map-panel"><MapView reports={visible} onSelect={setSelected} heat={heat}/><div className="map-heading"><span><MapPin size={16}/>Valledupar</span><button className={heat?'map-toggle selected':'map-toggle'} onClick={()=>setHeat(v=>!v)} aria-pressed={heat}><Layers size={16}/>{heat?'Ver puntos':'Ver concentración'}</button></div><div className="map-legend">{heat?<span>Círculos más intensos = más reportes abiertos cercanos.</span>:statuses.map(s=><span key={s}><i className={'dot d'+statuses.indexOf(s)}/>{s==='Atendido/Cerrado'?'Cerrado':statusLabel(s)}</span>)}</div></section>}
 </div>{tab==='Revisión'&&<p className="context-note"><ShieldCheck size={17}/>{pending.length} reportes pueden avanzar. Abre uno para revisar su evidencia. Este modo está disponible para probar el flujo y no representa a una autoridad.</p>}
 </>}
 <footer className="footer"><span>Vía Libre Valledupar · Demostración</span><span>Reportes y fotografías guardados solo en este navegador.</span></footer>
 </main>
 {create&&<CreateReport onClose={()=>setCreate(false)} onSaved={async(id)=>{setCreate(false);const data=await refresh();setNotice('Reporte recibido. Puedes seguirlo en Mis reportes.');if(data)setSelected(data.find(r=>r.id===id)||null);}}/>}
 {selected&&<Details report={selected} reviewer={reviewer} onClose={()=>setSelected(null)} onSaved={async()=>{const data=await refresh();if(data)setSelected(data.find(r=>r.id===selected.id)||null);setNotice('Revisión guardada en la demostración.');}}/>}
 </div>;
}
function CreateReport({onClose,onSaved}:{onClose:()=>void;onSaved:(id:string)=>void}){
 const [point,setPoint]=useState<[number,number]|null>(null),[photo,setPhoto]=useState<File|null>(null),[preview,setPreview]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[gps,setGps]=useState(false);
 const [observed,setObserved]=useState(()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);});
 useEffect(()=>{if(!photo){setPreview('');return;}const url=URL.createObjectURL(photo);setPreview(url);return()=>URL.revokeObjectURL(url);},[photo]);
 function locate(){setError('');if(!navigator.geolocation){setError('Tu navegador no permite GPS. Selecciona un punto en el mapa.');return;}setGps(true);navigator.geolocation.getCurrentPosition(p=>{setPoint([p.coords.latitude,p.coords.longitude]);setGps(false);},()=>{setError('No pudimos obtener tu ubicación. Selecciona un punto en el mapa o escribe las coordenadas.');setGps(false);},{enableHighAccuracy:true,timeout:10000});}
 async function submit(e:React.FormEvent<HTMLFormElement>){
 e.preventDefault();setError('');if(!point){setError('Selecciona la ubicación en el mapa o escribe las coordenadas.');return;}if(!photo){setError('Adjunta una foto para completar el reporte.');return;}
 const data=new FormData(e.currentTarget);data.set('lat',String(point[0]));data.set('lng',String(point[1]));data.set('observed',new Date(observed).toISOString());data.set('photo',photo);
 setBusy(true);try{const saved=await createReport(data);onSaved(saved.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 return <Modal title="Nuevo reporte" onClose={onClose} wide><form onSubmit={submit}><p className="modal-intro">Documenta el obstáculo y marca dónde ocurre.</p><div className="create-grid"><div className="form-column"><label>¿Qué está pasando?<select name="kind" required defaultValue=""><option value="" disabled>Selecciona una situación</option>{kinds.map(k=><option key={k}>{k}</option>)}</select></label><label>Dirección o referencia<input name="address" required maxLength={200} placeholder="Ej. Carrera 9 con calle 16"/></label><label>Fecha y hora de la observación<input type="datetime-local" name="observed" required value={observed} onChange={e=>setObserved(e.target.value)}/></label><label>Observación <span className="optional">(opcional)</span><textarea name="note" rows={3} maxLength={1000} placeholder="Describe cómo afecta el paso."/></label><label className="upload"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0]||null;if(f&&(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>5*1024*1024)){setError('Elige una foto JPG, PNG o WebP de hasta 5 MB.');e.target.value='';return;}setError('');setPhoto(f);}}/>{preview?<img src={preview} alt="Vista previa de la foto adjunta"/>:<><Camera size={28}/><strong>Adjuntar fotografía</strong><span>JPG, PNG o WebP · Hasta 5 MB</span></>}{photo&&<small>{photo.name} · Cambiar foto</small>}</label></div>
 <div className="location-column"><div className="location-title"><h3>Ubicación del reporte</h3><button className="secondary" type="button" onClick={locate} disabled={gps}><LocateFixed size={16}/>{gps?'Buscando…':'Usar mi ubicación'}</button></div><p className="small">Toca el mapa para colocar el punto.</p><MapView point={point} onPoint={setPoint}/><div className="coords"><label>Latitud<input type="number" step="any" min="-90" max="90" required value={point?.[0]??''} onChange={e=>setPoint([Number(e.target.value),point?.[1]??-73.249])}/></label><label>Longitud<input type="number" step="any" min="-180" max="180" required value={point?.[1]??''} onChange={e=>setPoint([point?.[0]??10.475,Number(e.target.value)])}/></label></div><div className="form-tip"><ShieldCheck size={20}/><p>El reporte y su foto se guardan solo en este navegador. La revisión y cualquier recompensa son simuladas.</p></div></div></div>
 {error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose} disabled={busy}>Cancelar</button><button type="submit" className="primary" disabled={busy}>{busy?'Guardando…':'Registrar reporte'}</button></div></form></Modal>;
}
function Details({report:r,reviewer,onClose,onSaved}:{report:Report;reviewer:boolean;onClose:()=>void;onSaved:()=>void}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[imageError,setImageError]=useState(false);
 const [decision,setDecision]=useState(next[r.status]?.[0]||'');useEffect(()=>{setDecision(next[r.status]?.[0]||'');},[r.status]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await reviseReport({id:r.id,status:decision,note:String(f.get('note')||'')});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal title="Detalle del reporte" onClose={onClose}><div className="detail-body"><div className="report-top"><span className={klass(r.status)}>{statusLabel(r.status)}</span><small>{r.example?'Reporte ficticio de ejemplo':'#'+r.id.slice(0,8).toUpperCase()}</small></div><h3 className="detail-title">{r.kind}</h3><p className="detail-address"><MapPin size={17}/>{r.address}</p>{r.photo&&!imageError?<img className="evidence" src={r.photo} alt={'Evidencia adjunta: '+r.kind} onError={()=>setImageError(true)}/>:<div className="no-photo"><Camera size={28}/><span>{r.example?'Ejemplo sin fotografía real':'No se pudo cargar la foto. Cierra y vuelve a abrir el reporte.'}</span></div>}<dl><div><dt>Observado</dt><dd>{date(r.observed)}</dd></div><div><dt>Coordenadas</dt><dd>{r.lat.toFixed(5)}, {r.lng.toFixed(5)}</dd></div></dl>{r.note&&<p className="detail-note">{r.note}</p>}
 {earned(r)&&<div className="reward-badge"><Wallet size={19}/>{cash(10000)} COP · Recompensa ficticia asignada</div>}<h3 className="timeline-title">Seguimiento</h3><ol className="timeline">{JSON.parse(r.history).map((h:{status:string;at:string;note:string},i:number)=><li key={i}><span className={'timeline-node d'+statuses.indexOf(h.status)}/><div><strong>{statusLabel(h.status)}</strong><small>{date(h.at)}</small><p>{h.note}</p></div></li>)}</ol>
 {reviewer&&(next[r.status]?.length>0)?<form className="review-form" onSubmit={save}><h3><ShieldCheck size={19}/>Revisión de demostración</h3><label>Siguiente estado<select value={decision} onChange={e=>setDecision(e.target.value)}>{next[r.status].map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select></label><label>Motivo de la decisión<textarea name="note" required maxLength={1000} rows={3} placeholder="Describe lo que observaste en la evidencia."/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar revisión'}</button></form>:reviewer?<p className="small">Este reporte ya finalizó su recorrido.</p>:<p className="small">Activa “Probar como revisor” para simular la siguiente etapa.</p>}</div></Modal>;
}
